var valor1;
var valor2;
valor1=prompt('Ingrese primer número:','');
valor2=prompt('Ingrese segundo número','');
var suma=parseInt(valor1)+parseInt(valor2);
var producto=valor1*valor2;
document.write(' la suma es ');
document.write(suma);
document.write('<br>');
document.write(' el producto es ');
document.write(producto);